import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Box, TextField, Button, Typography, Container } from "@mui/material";

const Register = () => {
  const navigate = useNavigate();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const handleRegister = (e) => {
    e.preventDefault();
    // Perform registration logic (e.g., call an API)
    if (password !== confirmPassword) {
      alert("Passwords do not match!");
      return;
    }
    console.log("Name:", name);
    console.log("Email:", email);
    console.log("Password:", password);
    // Navigate to home or login page after successful registration
    navigate("/login");
  };

  return (
    <Container maxWidth="sm" sx={{ marginTop: 4 }}>
      <Box sx={{ textAlign: "center", marginBottom: 4 }}>
        <Typography variant="h4" sx={{ fontWeight: "bold", marginBottom: 2 }}>
          Register
        </Typography>
        <Typography variant="body1" sx={{ marginBottom: 4 }}>
          Create an account to get started with Newsletter Generated By AI.
        </Typography>

        <form onSubmit={handleRegister}>
          <TextField
            fullWidth
            label="Name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
            sx={{ marginBottom: 2 }}
          />
          <TextField
            fullWidth
            label="Email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            type="email"
            required
            sx={{ marginBottom: 2 }}
          />
          <TextField
            fullWidth
            label="Password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            required
            sx={{ marginBottom: 2 }}
          />
          <TextField
            fullWidth
            label="Confirm Password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            type="password"
            required
            sx={{ marginBottom: 4 }}
          />
          <Button
            type="submit"
            variant="contained"
            color="primary"
            fullWidth
            sx={{ paddingY: 1.5, fontWeight: "bold" }}
          >
            Register
          </Button>
        </form>

        {/* Link to Login page */}
        <Box sx={{ marginTop: 2 }}>
          <Typography variant="body2">
            Already have an account?{" "}
            <Button
              onClick={() => navigate("/login")}
              sx={{ fontWeight: "bold", textTransform: "none" }}
            >
              Login Here
            </Button>
          </Typography>
        </Box>
      </Box>
    </Container>
  );
};

export default Register;
